### PR TITLE
Refactor templating and `find' statements

### PR DESCRIPTION
**Pull request by DanFerrer**
### Changes

- Create   ```createIssueTemplate``` to handle templating to avoid multiple assignments of ```innerHTML```

- Refactor ```find``` statements to implicit one liners

### Why was this needed

- Constant assignment to the DOM can affect performance and it's something I didn't think of until later in my dev career. I think it should be something to think about right away even as a beginner reading the blog post.

- Keeping up with the idea of modernizing the original blog post, lets show ES6 implicit returns for function bodies that can be summed up in one line.

### CODE REVIEW

**Comment by DanFerrer** [comment]
Thanks! Im not sure what you mean about the undefined check though. Do you mean check for the issues array length before running the rest of the function?

**Comment by elliotmrodriguez** [comment]
@DanFerrer Yes, I think something like this should work:

`const updateIssue = issues && issues.find(issueToClose => issueToClose.id === id);`

or

`const updateIssue = issues ? issues.find(issueToClose => issueToClose.id === id) : undefined; //or bomb or something`

As I look at this more there could be some better defensive coding around undefined `issuesList` , possibly by lifting it as a function arg (which would reduce some duplication too)

**Comment by DanFerrer** [comment]
I believe the iterator methods are already optimized for cases when you pass in an empty array so that might be redundant

I was thinking maybe instead, we do the check right when grab issues length:

```javascript
if (issues.length) {
        const updateIssue = issues.find(issueToClose => issueToClose.id === id);
        //rest of code
}
```
Or if there are cases where we know we might not get a valid issue from ```find``` we can do the check you suggested but after the find method since we know a bad id or empty array is gonna give us a ```null``` from find:

```javascript
const issues = this.issuesList(); 
const updateIssue = issues.find(issueToClose => issueToClose.id === id);

if (updateIssue) {
  //rest of code
}
```

**Comment by elliotrodriguez** [comment]
sorry for the delayed response @DanFerrer - nice work!

**Pull request merged**
